SHOW_VIEWER = True
MODE = "testing"
ARMS_3D = False
USE_IMAGES = True
ROBOT_TYPES = ARMS
TASK_TYPES = REACHERS
VIDEO_PATH = None
NEURAL_NET_ITERATIONS *= 0
NEURAL_NET_ITERATIONS += 2 * 10 ** 5
SAMPLES = 5

NAME = "uv"
