SHOW_VIEWER = False
MODE = "training"
ARMS_3D = False
USE_IMAGES = False
ROBOT_TYPES = RobotType.BAXTER_CYAN, RobotType.PR2_MAGENTA, RobotType.PEGGY
TASK_TYPES = REACHERS
VIDEO_PATH = None

NEURAL_NET_ITERATIONS *= 0
NEURAL_NET_ITERATIONS += 1000
